language: go

services:
  - docker

go:
  - 1.11.x
jobs:
  include:
    - stage: "tests"
      name: "unit tests"
      script:
        - cd scripts
        - sudo ./prepare_env.sh
        - "./start_dbs_test.sh"
        - cd .. ; ls ; sleep 20 ; go test -v ./...

    - stage: "build"
      name: "build dockers and tag latest"
      script:
        - if [[ $TRAVIS_COMMIT_MESSAGE == .*BUILD.* ]]; then sudo ./scripts/build_dockers.sh fi;

    - stage: "deploy"
      name: "restart service"
      script:
        - if [[ $TRAVIS_COMMIT_MESSAGE == .*BUILD.* ]]; then ssh -i ~/5factorial_id_rsa.pem ubuntu@95.163.180.8 sudo systemctl restart 5factorial fi;

before_install:
  - openssl aes-256-cbc -K $encrypted_147bdc689a1a_key -iv $encrypted_147bdc689a1a_iv
    -in 5factorial_id_rsa.pem.enc -out ~/5factorial_id_rsa.pem -d
  - chmod 600 ~/5factorial_id_rsa.pem
  - ssh-keyscan -H 95.163.180.8 >> ~/.ssh/known_hosts
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

env:
  global:
    - secure: kw5Gq94U33RIHgiVQJEIgKH5cWoNy63tgdUxAFFYzM9ccUkyWfyk9r2EMPshl2BI51H53MjWuT/L9Yc2YOaraMqBy2uccCG6g9fUSiJMslMbVrHqvJoUuZRtPX5CPLf1bNGv7aCotPUuoI/QUzaEsBIA/N+XiaX1bXef8J8od8dYCe88acFZBFjZEdPfyJAgEAUISh7Q70hGe7uupSn/CRyaIqqAfgXLMzEL1P4PMEHzTvafe1WH4gwK2XnjbkJHKHmYk54iFzlQ5Q+DLVwj+mbbWJTDTYhrhFOcHLLfwLud9B2oebR14PofmcuXQ4fZ9aN8scYv7p57m/T3OFR3Q8QGsm2Asz/OA7hGANCbk9nh48VQKOTN+6LxtKgOWWObC7jhf9jT4ILwvpBz4PZEs40EAkv2VlhP83PZAsARoe6t2mO+GXsGd5pdXdoKsoif6TKGpSOujoTeaG5yg42NyKwDibfNdYL/vSimVohTkDzRmmyrTgwbqTwMf8e2K32YLNhUazhv85FAC7NUXY4JecxzoWIjrgqwkQeK/o7gos5xOoJ2eW5lK8fidaSxEjXbwC8kZ5+psRS3S3cCcM1NXblhJ52CNPd7Y4b9jDARiKgqguibzBslH6BA66vGSXc7uICSoVXXOk+9W9dgxbXexSFHinP40YmeTKTDlBxfzgc=
    - secure: YJbi9lE35fHC2sIyOb6WvAYPrSXKOJsEeb7+chLW2Gb5+H7sC68BGlLacC1gNoiWDKw3mgZnxmnvGYRqJhOBRgWXCAN2axA/JGtss95CxES8PGltmZ9HuFJ7bMDfsK5M6n98LhIMkrJLETwGR5GJtGiRQ+l2KsUcG9ZXZGMwLu69mllp5uPUFkl3mE0uuUMRb8TrI9CSzBsAKn8B9nafnYUjryMIVmdSqBePTqoNZz7sDWQh7FNgmNcvcZsJrGeTLUbKh3FStIGU5VGJ8mg+/LdTDRzg4aSHrmBfhoHTck/hhxufWdw0tIfq/jtkRE8kIxcp9vTUr5ouRDf8TCWAQaFQRMxIc/d96nO5VFNlxCzOeHGbmk6UWNQJtFXxmbd9C/eVlO5mWZssMGXuaYHc52Lpooacf/Wb84ddDck4yTmvdSm+2Fm924JUBb6t0U+Eqn4hWX3/NP/7d5GK2IYEbqIJI04zrAfONtSjkcHWah61w399PooFFkjzMaqd9FRS40CUt4VHoZKMfbl6csivmQf2OWM89du61DNOl04B30kqU3QdzL2m5cAsBdrsvRhobVHj1NtngHaqYVz1kyMPoQZy+7XZrKP2rsF6fyESmRZ3BJCj4tYqBRhd4MGIcyVywmkIOFEHWbU88q0ql3GZsYULadXxc6PlQNsRm6zH2bA=
