language: go

services:
- docker

go:
- 1.11.x

script:
- chmod 600 ~/5factorial_id_rsa.pem
- ssh-keyscan -H 95.163.180.8 >> ~/.ssh/known_hosts
# - cd scripts
# - sudo ./prepare_env.sh
# - "./start_dbs_test.sh & sleep 60 ; cd .. ; go test -v ./..."
- "cd .. ; ls ; sleep 10 ; go test -v ./..."

before_install:
- openssl aes-256-cbc -K $encrypted_147bdc689a1a_key -iv $encrypted_147bdc689a1a_iv
  -in 5factorial_id_rsa.pem.enc -out ~/5factorial_id_rsa.pem -d
- cd scripts 
- sudo ./prepare_env.sh 
- ./start_dbs_test.sh
