language: go

services:
- docker

go:
- 1.11.x

script:
- chmod 600 ~/5factorial_id_rsa.pem
- ssh-keyscan -H 95.163.180.8 >> ~/.ssh/known_hosts
# - cd scripts
# - sudo ./prepare_env.sh
# - "./start_dbs_test.sh & sleep 60 ; cd .. ; go test -v ./..."
- "cd .. ; ls ; sleep 10 ; go test -v ./..."
- docker build -t smetk/5factorial-auth:`git log -1 --pretty=%h` -f ./third-party/auth/Dockerfile .
- docker build -t smetk/5factorial-core:`git log -1 --pretty=%h` -f ./third-party/server/Dockerfile .
- docker build -t smetk/5factorial-worker:`git log -1 --pretty=%h` -f ./third-party/worker/Dockerfile .
- docker build -t smetk/5factorial-chat:`git log -1 --pretty=%h` -f ./third-party/chat/Dockerfile .
- docker build -t smetk/5factorial-game:`git log -1 --pretty=%h` -f ./third-party/game/Dockerfile .
- docker push smetk/5factorial-auth & docker push smetk/5factorial-core & docker push smetk/5factorial-worker &
  docker push smetk/5factorial-chat & docker push smetk/5factorial-game

before_install:
- openssl aes-256-cbc -K $encrypted_147bdc689a1a_key -iv $encrypted_147bdc689a1a_iv
  -in 5factorial_id_rsa.pem.enc -out ~/5factorial_id_rsa.pem -d
- cd scripts 
- sudo ./prepare_env.sh 
- ./start_dbs_test.sh
