language: go

go:
- 1.11.x

# git:
#   depth: 1

script:
  - go mod init ; go mod vendor
  - cd scripts
  - ./start.sh
  - cd ..
  - go tool cover -func c.out
  - go test -coverpkg=./... -coverprofile=c.out ./...