// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  controllers

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AvatarLinkResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AvatarLinkResponse ) UnmarshalJSON([]byte) error { return nil }
func ( AvatarLinkResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AvatarLinkResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AvatarLinkResponse *AvatarLinkResponse
