// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package controllers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers(in *jlexer.Lexer, out *UsersCountInfoResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "count":
			out.Count = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers(out *jwriter.Writer, in UsersCountInfoResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UsersCountInfoResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UsersCountInfoResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UsersCountInfoResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UsersCountInfoResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers(l, v)
}
func easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers1(in *jlexer.Lexer, out *SingUpRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "login":
			out.Login = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers1(out *jwriter.Writer, in SingUpRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"email\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SingUpRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SingUpRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SingUpRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SingUpRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers1(l, v)
}
func easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers2(in *jlexer.Lexer, out *SignUpResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers2(out *jwriter.Writer, in SignUpResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SignUpResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SignUpResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SignUpResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SignUpResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers2(l, v)
}
func easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers3(in *jlexer.Lexer, out *ProfileUpdateResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "nickname":
			out.Nickname = string(in.String())
		case "score":
			out.Score = int(in.Int())
		case "avatar_link":
			out.AvatarLink = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers3(out *jwriter.Writer, in ProfileUpdateResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"nickname\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Nickname))
	}
	{
		const prefix string = ",\"score\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Score))
	}
	{
		const prefix string = ",\"avatar_link\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AvatarLink))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProfileUpdateResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProfileUpdateResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProfileUpdateResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProfileUpdateResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers3(l, v)
}
func easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers4(in *jlexer.Lexer, out *ProfileUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "avatar":
			out.Avatar = string(in.String())
		case "old_password":
			out.OldPassword = string(in.String())
		case "new_password":
			out.NewPassword = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers4(out *jwriter.Writer, in ProfileUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Avatar))
	}
	{
		const prefix string = ",\"old_password\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.OldPassword))
	}
	{
		const prefix string = ",\"new_password\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.NewPassword))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProfileUpdateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProfileUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1e73d8aEncodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProfileUpdateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProfileUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1e73d8aDecodeGithubComGoParkMailRu201915factorialTeamInternalPkgControllers4(l, v)
}
