global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'core'
    static_configs:
      - targets:
        - 'localhost:5051'

  - job_name: 'system'
    static_configs:
      - targets:
        - 'nodeexporter:9100'