global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'core'
    static_configs:
      - targets:
        - 'server-go:5051'

  - job_name: 'system'
    static_configs:
      - targets:
        - 'node_exporter:9100'