version: '3'
services:
  #  TODO(): авторизация при подключении к бд
  mongo-user:
    container_name: 5factorial-user-mongo
    command: mongod --port 27031
    image: mongo:4.0
    ports:
      - '27061:27031' # map port to none standard port, to avoid conflicts with locally installed mongodb.
#    logging:
#      driver: "none"

  mongo-session:
    container_name: 5factorial-session-mongo
    command: mongod --port 27032
    image: mongo:4.0
    ports:
      - '27062:27032' # map port to none standard port, to avoid conflicts with locally installed mongodb.
#    logging:
#      driver: "none"

  mongo-chat:
    container_name: 5factorial-chat-global-mongo
    command: mongod --port 27033
    image: mongo:4.0
    ports:
      - '27063:27033' # map port to none standard port, to avoid conflicts with locally installed mongodb.
    logging:
      driver: "none"
  
  auth-go:
    container_name: 5factorial-back-auth
    restart: always
    build:
      context: ../.
      dockerfile: ./third-party/auth/Dockerfile
    volumes:
      - '/etc/5factorial:/etc/5factorial'
    ports:
      - '5000:5000'
    depends_on:
      - mongo-user
      - mongo-session
#    logging:
#      driver: "none"