version: '3'
services:
  mongo-user:
    container_name: 5factorial-user-mongo-1
    command: mongod --port 27031
    image: mongo:4.0
    ports:
      - '27061:27031'

  mongo-user-2:
    container_name: 5factorial-user-mongo-2
    command: mongod --port 27031
    image: mongo:4.0
    ports:
      - '27071:27031'

  mongo-user-3:
    container_name: 5factorial-user-mongo-3
    command: mongod --port 27031
    image: mongo:4.0
    ports:
      - '27081:27031'

  mongo-session:
    container_name: 5factorial-session-mongo-1
    command: mongod --port 27032
    image: mongo:4.0
    ports:
      - '27062:27032'

  mongo-session-2:
    container_name: 5factorial-session-mongo-2
    command: mongod --port 27032
    image: mongo:4.0
    ports:
      - '27072:27032'

  mongo-session-3:
    container_name: 5factorial-session-mongo-3
    command: mongod --port 27032
    image: mongo:4.0
    ports:
      - '27082:27032'

  mongo-chat:
    container_name: 5factorial-chat-global-mongo-test
    command: mongod --port 27033
    image: mongo:4.0
    ports:
      - '27063:27033'

  auth-go:
    container_name: 5factorial-back-auth-1
    restart: always
    build:
      context: ../.
      dockerfile: ./third-party/auth/Dockerfile
    volumes:
      - '/etc/5factorial:/etc/5factorial'
    ports:
      - '5000:5000'
    depends_on:
      - mongo-user
      - mongo-session

  mongo-user-4:
    container_name: 5factorial-user-mongo-4
    command: mongod --port 27031
    image: mongo:4.0
    ports:
      - '27091:27031'

  mongo-session-4:
    container_name: 5factorial-session-mongo-4
    command: mongod --port 27032
    image: mongo:4.0
    ports:
      - '27092:27032'