version: '3'
networks:
  default:
    external:
      name: 5factorial-net

services:
  mongo-user:
    container_name: 5factorial-user-mongo
    command: mongod --port 27031
    image: mongo:4.0
    volumes:
      - '/data/db/user:/data/db'
    ports:
      - '27051:27031' # map port to none standard port, to avoid conflicts with locally installed mongodb.

  mongo-session:
    container_name: 5factorial-session-mongo
    command: mongod --port 27032
    image: mongo:4.0
    volumes:
      - '/data/db/session:/data/db'
    ports:
      - '27052:27032' # map port to none standard port, to avoid conflicts with locally installed mongodb.

  #  mongo-chat-global:
  #    container_name: 5factorial-chat-global-mongo
  #    command: mongod --port 27033
  #    image: mongo:4.0
  #    volumes:
  #      - '/data/db/chat_global:/data/db'
  #    ports:
  #      - '27053:27033' # map port to none standard port, to avoid conflicts with locally installed mongodb.

  auth-go:
    container_name: 5factorial-back-auth
    restart: always
    image: smetk/5factorial-auth:latest
    volumes:
      - '/etc/5factorial:/etc/5factorial'
    depends_on:
      - mongo-user
      - mongo-session

  server-go:
    container_name: 5factorial-back
    restart: always
    image: smetk/5factorial-core:latest
    volumes:
      - '/var/www/media/factorial:/var/www/media/factorial'
      - '/etc/5factorial:/etc/5factorial'
    ports:
      - '8001:5051'
    depends_on:
      - auth-go

  worker-go:
    container_name: 5factorial-worker
    restart: always
    image: smetk/5factorial-worker:latest
    volumes:
      - '/etc/5factorial:/etc/5factorial'
    depends_on:
      - mongo-session

  #  chat-go:
  #    container_name: 5factorial-back-chat
  #    restart: always
  #    image: smetk/5factorial-chat:latest
  #    volumes:
  #      #     - '/var/www/media/factorial:/var/www/media/factorial'
  #      - '/etc/5factorial:/etc/5factorial'
  #    ports:
  #      - '8002:5052'
  #    depends_on:
  #      - mongo-chat-global
  #      - auth-go

  game-go:
    container_name: 5factorial-back-game
    restart: always
    image: smetk/5factorial-game:latest
    volumes:
      - '/etc/5factorial:/etc/5factorial'
    ports:
      - '8003:5053'
    depends_on:
      - auth-go

  donation-go:
    container_name: 5factorial-back-ndex
    restart: always
    image: smetk/5factorial-donation:latest
    ports:
      - '8004:5054'
